//Scenario 1
GET http://localhost:3049/todos/?status=TO%20DO
###

//Scenario 2
GET http://localhost:3049/todos/?priority=HIGH
###

//Scenario 3
GET http://localhost:3049/todos/?priority=HIGH&status=IN%20PROGRESS
###

//Scenario 4
GET http://localhost:3049/todos/?search_q=Buy
###

//Scenario 5
GET http://localhost:3049/todos/?category=WORK&status=DONE
###

//Scenario 6
GET http://localhost:3049/todos/?category=HOME
###

//Scenario 7
GET http://localhost:3049/todos/?category=LEARNING&priority=HIGH
###

//API-2
GET http://localhost:3049/todos/1/
###

//API-3
GET http://localhost:3049/agenda/?date=2020-11-22
###

//API-4
POST http://localhost:3049/todos/

{
    "id":2,
    "todo":"Finalize event theme",
    "priority":"LOW",
    "status":"TO DO",
    "category":"HOME",
    "dueDate":"2021-02-22"
}
###

//API-5
//Scenario 1
PUT http://localhost:3049/todos/1/

{
    "status":"DONE"
}
###
//Scenario 2
PUT http://localhost:3049/todos/1/
{
    "priority":"HIGH"
}
###
//Scenario 3
PUT http://localhost:3049/todos/2/
{
    "todo":"Clean the garden"
}
###
//Scenario 4
PUT http://localhost:3049/todos/2/
{
    "category":"LEARNING"
}
###
//Scenario 5
PUT http://localhost:3049/todos/2/
{
    "dueDate":"2021-01-12"
}
###

#API-6
DELETE http://localhost:3049/todos/2/
###


